Support mjs/cjs config file extension for prettier
vscode-icons/vscode-icons pull request #2612
Opened 2020-09-11 12:19 UTC by shrujalshah28

**Changes proposed:**

- [x] Add
- [ ] Delete
- [ ] Fix
- [ ] Prepare

---
See [Prettier release note](https://prettier.io/blog/2020/08/24/2.1.0.html#support-cjs-and-json5-configuration-files-8890httpsgithubcomprettierprettierpull8890-8957httpsgithubcomprettierprettierpull8957-by-fiskerhttpsgithubcomfisker)

2020-09-15 17:14 UTC, robertohuertasm requested changes
According to the release notes it says `cjs` and `json5` not a mention to `mjs`extension. Can you clarify please?

2020-09-16 05:01 UTC, shrujalshah28 commented
My bad. Code updated. Removed `.mjs` and added `json5`.

2020-09-16 12:57 UTC, KingDarBoja approved these changes

2020-09-17 17:21 UTC, robertohuertasm approved these changes

2020-09-17 17:21 UTC, merged