Update lint-staged supported extensions
vscode-icons/vscode-icons pull request #2878
Opened 2021-12-08 04:52 UTC by rivajunior

**Changes proposed:**

- [x] Add
- [ ] Delete
- [ ] Fix
- [ ] Prepare

Since lint-staged [v12.1.0](https://github.com/okonet/lint-staged/releases/tag/v12.1.0) it support `.mjs` for its configuration.

I've removed the postfix of the icon filename and icon title tag to be more embracing, because lint-staged also support `lint-staged.config` filename with different extensions allowed.

2021-12-21 10:19 UTC, robertohuertasm approved these changes
LGTM 🚀 Thanks for your contribution ❤️

2021-12-21 10:21 UTC, robertohuertasm commented
It seems there's something wrong with the tests...

2021-12-22 14:49 UTC, robertohuertasm requested changes
Let's check why the tests are failing

2022-02-07 23:33 UTC, rivajunior commented
The merging of the two lintstaged objects fixes the tests

```typescript
{
      icon: 'lintstaged',
      extensions: ['lintstagedrc'],
      filenamesGlob: ['.lintstagedrc', 'lint-staged.config'],
      extensionsGlob: ['js', 'json', 'yaml', 'yml', 'cjs', 'mjs'],
      filename: true,
      format: FileFormat.svg,
},
```

but I think it would leading to a wrong result match in vscode, because the filename 'lint-staged.config' does't support 'json', 'yaml' and 'yml' extensions. That's why I've created two separated configs.

What you guys (@robertohuertasm @imartingon ) think?

2022-02-08 15:23 UTC, robertohuertasm commented
Let me look into this.

2022-02-10 19:32 UTC, robertohuertasm requested changes

2022-02-10 19:32 UTC, robertohuertasm commented on src/iconsManifest/supportedExtensions.ts
> +      filenamesGlob: ['lint-staged.config'],
add `extensions: []`, that should do the trick to pass the tests.

2022-02-11 03:19 UTC, xiaoxiangmoe commented
Hi, all.
I found linstaged source codes has a list for config file names.

https://github.com/okonet/lint-staged/blob/e7b6412fb128f314346e28329c17a676cf691135/lib/loadConfig.js#L13-L25

```js
/**
 * The list of files `lint-staged` will read configuration
 * from, in the declared order.
 */
const searchPlaces = [
  'package.json',
  '.lintstagedrc',
  '.lintstagedrc.json',
  '.lintstagedrc.yaml',
  '.lintstagedrc.yml',
  '.lintstagedrc.mjs',
  '.lintstagedrc.js',
  '.lintstagedrc.cjs',
  'lint-staged.config.mjs',
  'lint-staged.config.js',
  'lint-staged.config.cjs',
]
```

So I copy this and create a PR.

see https://github.com/vscode-icons/vscode-icons/pull/2889/files#diff-d2e737a639e4d3439dac2e1e9f2597e1dd55a743854cdf2ea939dd5131afbf6fL2378-L2381

2022-02-11 09:55 UTC, closed without merging