Add '.tailwind' and '.tailwindrc' to glob
vscode-icons/vscode-icons pull request #2899
Opened 2022-01-25 07:52 UTC by mkvlrn

**Changes proposed:**

- [x] Add
- [ ] Delete
- [ ] Fix
- [ ] Prepare

Add these 2 items to glob of file names for the tailwind configuration file to match some others such as postcss, eslint, jest, etc.

2022-02-07 23:21 UTC, robertohuertasm requested changes

2022-02-07 23:21 UTC, robertohuertasm commented on src/iconsManifest/supportedExtensions.ts
> +      filenamesGlob: ['tailwind', 'tailwind.config', ".tailwind", ".tailwindrc"],
Use single quotes.

2022-02-08 00:42 UTC, mkvlrn commented on src/iconsManifest/supportedExtensions.ts
> +      filenamesGlob: ['tailwind', 'tailwind.config', ".tailwind", ".tailwindrc"],
done

2022-02-08 09:17 UTC, robertohuertasm approved these changes
LGTM 🚀 Thanks for your contribution ❤️

2022-02-08 09:37 UTC, merged