Add support for SVG and PNG-based drawio files
vscode-icons/vscode-icons pull request #2987
Opened 2022-04-23 05:10 UTC by cathaypacific8747

**Changes proposed:**

- [x] Add

[Draw.io](https://github.com/hediet/vscode-drawio) supports [editing](https://github.com/hediet/vscode-drawio/blob/8da9fb55cc55825fa4d2778f79b7f534a8d77bc8/src/DrawioEditorService.ts#L170-L177) `*.drawio.png`, `*.drawio.svg`, `*.dio.svg`, `*.dio.png` files.

2022-04-23 11:08 UTC, sasial-dev requested changes
Your lints (and my local tests!) failed on this one.
Make sure to simplify - and test locally!

2022-04-23 11:08 UTC, sasial-dev commented on src/iconsManifest/supportedExtensions.ts
>        extensionsGlob: [],
Simplify this for the same result!
```suggestion
      extensions: ['drawio', 'dio'],
      filenamesGlob: ['.drawio', '.dio'],
      extensionsGlob: ['png', 'svg'],
```

2022-04-23 11:09 UTC, sasial-dev commented on src/iconsManifest/supportedExtensions.ts
>        extensionsGlob: [],
Test locally that the above satisfies `.drawio`, `.drawio.svg`, `.drawio.png`

2022-05-21 14:55 UTC, robertohuertasm approved these changes
LGTM 🚀 Thanks for your contribution ❤️

2022-05-21 14:56 UTC, merged