feat(icon): add @sapphire/framework cli icon
vscode-icons/vscode-icons pull request #3175
Opened 2022-11-02 03:38 UTC by kaname-png

_**Fixes #IssueNumber**_

**Changes proposed:**

- [x] Add
- [ ] Delete
- [ ] Fix
- [ ] Prepare

2022-11-02 06:03 UTC, favna requested changes

2022-11-02 06:03 UTC, favna commented on src/iconsManifest/supportedExtensions.ts
> +      extensions: ['.sapphirerc.json', '.sapphirerc'],
The sapphire CLI also supports yaml files.

2022-11-02 22:28 UTC, favna submitted a review, later dismissed

2023-01-23 10:27 UTC, robertohuertasm approved these changes
icon reworked

2023-01-23 14:07 UTC, robertohuertasm approved these changes

2023-01-23 14:09 UTC, merged