feat(icon): add vercel folder support
vscode-icons/vscode-icons pull request #3237
Opened 2023-02-19 16:37 UTC by Hacksore

- Add vercel folder support 
- Rename file icon `file_type_zeit.svg` -> `file_type_vercel.svg`

**Changes proposed:**

- [x] Add

Example:
![image](https://user-images.githubusercontent.com/996134/219961507-a6f4ab2d-485a-47e7-8fb0-c994748633c6.png)

2023-04-10 17:49 UTC, robertohuertasm commented
The background color of the folder doesn't work for dark themes. Consider using another color. Grey would work for light and dark themes and it also works with the icon.

2023-04-10 20:50 UTC, Hacksore commented
@robertohuertasm Here they are side by side with the default theme in a crude mock up. If you think black is not feasible can you suggest the ideal color for the gray?

![image](https://user-images.githubusercontent.com/996134/230995561-90e85522-ebe5-447b-a124-95ddc57e9964.png)

2023-04-10 21:22 UTC, robertohuertasm commented
That gray should be ok 😊

2023-04-11 21:54 UTC, Hacksore commented
@robertohuertasm ready for a review again.

2023-04-23 18:49 UTC, robertohuertasm requested changes

2023-04-23 18:49 UTC, robertohuertasm commented on src/iconsManifest/supportedExtensions.ts
> +      icon: 'vercel',
you must also change the name of the light icon

2023-04-23 18:49 UTC, robertohuertasm commented on src/iconsManifest/supportedFolders.ts
> +      icon: 'vercel',
you still need to provide an opened version of the folder. Look for other folders in the extension to see how it's done.

2023-08-05 23:12 UTC, robertohuertasm approved these changes
LGTM 🚀 Thanks for your contribution ❤️

2023-08-05 23:16 UTC, merged