Update mediawiki file type
vscode-icons/vscode-icons pull request #3474
Opened 2024-03-31 11:09 UTC by Kleywalker

_**Fixes #IssueNumber**_

**Changes proposed:**

- [x] Add
- [x] Delete

Update mediawiki file type

2024-03-31 11:26 UTC, Kleywalker commented
Based on the official small icon: https://commons.wikimedia.org/wiki/File:MediaWiki-2020-small-icon.svg#/media/File:MediaWiki-2020-small-icon.svg

2024-05-04 21:13 UTC, robertohuertasm requested changes
Hi @Kleywalker, thank you for the contribution. Unfortunately, the size of the new icon is 12kb and we aim for 2kb. We should optimize it a little bit.

2024-06-01 16:10 UTC, robertohuertasm submitted a review, later dismissed
LGTM 🚀 Thanks for your contribution ❤️

2024-06-01 16:15 UTC, robertohuertasm approved these changes

2024-06-01 16:25 UTC, merged