feat(icon): supported `.slnx` file
vscode-icons/vscode-icons pull request #3482
Opened 2024-04-14 16:58 UTC by frg2089

Microsoft began experimenting with the publishing of an XML-based solution format, and it has the extension `.slnx`.

reference: https://schwabencode.com/blog/2024/04/10/welcome-new-visual-studio-slnx-solution-file

**Changes proposed:**

- [x] Add
- [ ] Delete
- [ ] Fix
- [ ] Prepare

2024-04-16 12:09 UTC, remcohaszing requested changes

2024-04-16 12:09 UTC, remcohaszing commented on src/iconsManifest/supportedExtensions.ts
> +    },
This specifies that the XML language should use the `sln` icon.

What I think you intended to do, was update the existing definition for the `sln` icon and add `slnx` to the existing list of extensions. Additionally you should add update the list of extensions for the `sln2` icon below.

2024-04-17 09:31 UTC, remcohaszing approved these changes

2024-05-03 22:22 UTC, robertohuertasm requested changes

2024-05-03 22:22 UTC, robertohuertasm commented on src/iconsManifest/supportedExtensions.ts
> +      extensions: ['sln', slnx'],
there´s a `´` missing

2024-05-03 22:22 UTC, robertohuertasm commented on src/iconsManifest/supportedExtensions.ts
> +      extensions: ['sln', slnx'],
Same here.

2024-05-04 04:18 UTC, frg2089 commented on src/iconsManifest/supportedExtensions.ts
> +      extensions: ['sln', slnx'],
```suggestion
      extensions: ['sln', 'slnx'],
```

2024-05-04 04:18 UTC, frg2089 commented on src/iconsManifest/supportedExtensions.ts
> +      extensions: ['sln', slnx'],
```suggestion
      extensions: ['sln', 'slnx'],
```

2024-05-04 21:15 UTC, robertohuertasm approved these changes

2024-05-04 21:15 UTC, merged