feat(icons): add oxlint icon
vscode-icons/vscode-icons pull request #3604
Opened 2024-10-13 17:15 UTC by DonIsaac

**Changes proposed:**

- [x] Add
- [ ] Delete
- [ ] Fix
- [ ] Prepare

Adds an icon for [Oxlint](https://github.com/oxc-project/oxc) configuration files.

2024-12-02 14:47 UTC, remcohaszing requested changes
Thanks! This looks mostly good.

Please adjust the icon according to https://github.com/vscode-icons/vscode-icons/wiki/Contributing. We also aim towards a (soft) maximum file size of 2KB. >10KB exceeds this limit quite a lot.

Some tips you can do to make the icon smaller:
- Replace shapes with paths
- Merge paths of the same color
- Remove unused paths
- Remove useless groups
- Remove useless attributes
- Remove useless whitespace
- Round numbers while saving. Usually 2 digits suffice.

2025-01-13 04:25 UTC, Boshen commented
The icon has been reduced to 2.49 KB.

2025-01-13 04:32 UTC, closed without merging

2025-01-13 09:33 UTC, robertohuertasm commented
@DonIsaac why did you close this?

2025-01-13 09:36 UTC, Boshen commented
Closed by https://github.com/vscode-icons/vscode-icons/pull/3665

2025-01-13 09:48 UTC, robertohuertasm commented
Oh, sorry, I didn't see that! Thank you @Boshen