feat(icon): add Docusaurus config
vscode-icons/vscode-icons pull request #3645
Opened 2024-12-17 14:38 UTC by jakeboone02

**Changes proposed:**

- [x] Add

- [Home page](https://docusaurus.io/)
- [Icon source](https://github.com/facebook/docusaurus/blob/c5a6c26d94804c91c421904be73c1397da89be6a/website/static/img/docusaurus.svg)
- [Supported extension source](https://github.com/facebook/docusaurus/blob/c5a6c26d94804c91c421904be73c1397da89be6a/packages/docusaurus/src/server/config.ts#L21)

2024-12-29 14:49 UTC, robertohuertasm requested changes
I know that this is an icon that would appear probably once in a codebase, but if you could reduce the size a little bit, it would be fantastic.  We aim for 2kb. I take it may not be possible to get that, but at least 4kb would be desirable.

2024-12-29 16:52 UTC, jakeboone02 commented
Sure, let me see what I can do.

2024-12-31 00:12 UTC, jakeboone02 commented
@robertohuertasm I got it down to 2.67 KB. I might actually submit a similar version to the Docusaurus team since it's virtually the same as the original but less than half the size.

2024-12-31 20:47 UTC, jakeboone02 commented
Got it down below 2K with aa91d69eee889d290459a1326967f50c9d9604e4

2025-01-01 18:16 UTC, robertohuertasm commented
@jakeboone02 that was really impressive! Well done and thank you for your contribution! ❤️

2025-01-01 18:17 UTC, robertohuertasm approved these changes
LGTM 🚀

2025-01-01 18:17 UTC, merged