refactor(icon): update css folder icon
vscode-icons/vscode-icons pull request #3652
Opened 2024-12-24 01:03 UTC by jonrandahl

With the [official release of the CSS icon](https://github.com/CSS-Next/logo.css), this PR he updates the css folder icons currently using the old icon to use the new icon.

Changes proposed:

- icons/folder_type_css.svg
  - All colours were updated to use rebeccapurple.
  - The icon was positioned to sit on the document the same as the previous icon.
  - The file was optimised and minified using SVGOMG.
- icons/folder_type_css_opened.svg
  - All colours were adjusted to mirror the HSL recommendations from the VSCode-Icon project  documentation: [Contributing with Icons](https://github.com/vscode-icons/vscode-icons/wiki/Contributing#contributing-with-icons)
  - The file was optimised and minified using SVGOMG.

2024-12-29 14:44 UTC, robertohuertasm requested changes
Hi @jonrandahl, thanks for your contribution. I've looked into the icons and I think it would be better to use another tone of purple for the closed folder, otherwise, the css icon and the folder seem to be the same thing.

Other than that, everything else seems ok. Looking forward to merging this.

As an extra request, can you keep the old icons and rename them with a "2" suffix? See [this as an example](https://github.com/vscode-icons/vscode-icons/blob/master/icons/file_type_actionscript2.svg). We have received multiple requests from users wanting to keep the old icon, and this would allow people to customize them using the custom icon functionality we provide. Thanks!

2024-12-30 00:14 UTC, jonrandahl commented
@robertohuertasm, while I'm in no rush and definitely do not want to take up your time during the holiday period I may need some guidance on the failing tests for the changes on the supported extensions/folders files when you have time?

2024-12-30 10:46 UTC, JimiC commented
> @robertohuertasm, while I'm in no rush and definitely do not want to take up your time during the holiday period, I may need some guidance on the failing tests for the changes on the supported extensions/folders files when you have time?

It's a formatting issue with the `css2map` declaration.
The file should have been formatted with `Prettier`.

2024-12-30 10:53 UTC, JimiC commented
Since we are talking about colors. If it was up to me I would had used the color tone of the open folder for the closed one (to make the `css` part distinguishable, an not the folder) and an even lighter tone for the opened one. At least that was my guide when I was creating the icons.

2025-01-05 02:01 UTC, jonrandahl commented
Thanks for your guidance @JimiC, greatly appreciated! 
🎉 Happy New Year!!! 🎉

2025-01-09 14:32 UTC, jonrandahl commented
@robertohuertasm just letting you know I've resolved the issues with both the failing tests as well as merging the latest updates onto this PR. Hope this helps and once again happy new year! 🎉

2025-01-09 18:51 UTC, robertohuertasm approved these changes
This is great! Thank you so much for this PR. Really appreciate it! ❤️

2025-01-09 18:56 UTC, merged